import type { Activity } from "@/lib/types"

function iso(date: string) {
  return new Date(date).toISOString()
}

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: "act_spacex",
    title: "SpaceX launch watch party",
    description:
      "Projector, snacks, and the countdown. We watch the next SpaceX launch together — commentary optional, awe required.",
    type: "social",
    tags: ["Space", "Launch", "Watch party"],
    lookingFor: ["Space fans", "Night owls"],
    location: { type: "in-person", city: "Belgrade", venue: "Dorćol rooftop" },
    startAt: iso("2026-08-22T21:00:00+02:00"),
    endAt: iso("2026-08-22T23:30:00+02:00"),
    isFlexible: false,
    capacity: null,
    joinPolicy: "auto",
    headcount: { mode: "estimate", about: 15 },
    creatorId: "user_marko",
    creatorName: "Marko Njegomir",
    creatorAvatar: null,
    memberCount: 4,
    status: "open",
    createdAt: iso("2026-08-14T22:00:12+02:00"),
    updatedAt: iso("2026-08-14T22:00:12+02:00"),
    visibility: "public",
    images: [],
  },
  {
    id: "act_imagine",
    title: "Make a short film with Grok Imagine 2.0",
    description:
      "A weekend to actually finish something: a 60–90 second film. Taste > tools. Request to join — small crew, not a crowd.",
    type: "film",
    tags: ["Film", "AI", "Grok"],
    lookingFor: ["Writer", "Editor", "Visual taste"],
    location: { type: "hybrid", city: "Belgrade", venue: "Studio / Discord" },
    startAt: iso("2026-08-29T11:00:00+02:00"),
    endAt: iso("2026-08-30T20:00:00+02:00"),
    isFlexible: false,
    capacity: 5,
    joinPolicy: "manual",
    headcount: { mode: "range", min: 3, max: 5 },
    creatorId: "user_marko",
    creatorName: "Marko Njegomir",
    creatorAvatar: null,
    memberCount: 2,
    status: "open",
    createdAt: iso("2026-08-14T22:00:11+02:00"),
    updatedAt: iso("2026-08-14T22:00:11+02:00"),
    visibility: "public",
    images: [],
  },
  {
    id: "act_connect",
    title: "Let’s build a project that helps connect people",
    description:
      "No slide deck. We talk, we sketch, we ship a first version. If you’ve felt the same itch, come.",
    type: "software",
    tags: ["Community", "Product", "Build"],
    lookingFor: ["Builder", "Designer", "Product"],
    location: { type: "in-person", city: "Belgrade", venue: "KC Grad" },
    startAt: iso("2026-08-23T17:00:00+02:00"),
    endAt: iso("2026-08-23T21:00:00+02:00"),
    isFlexible: true,
    capacity: null,
    joinPolicy: "auto",
    headcount: { mode: "open" },
    creatorId: "user_bogdan",
    creatorName: "Bogdan Ljubinkovic",
    creatorAvatar: null,
    memberCount: 3,
    status: "open",
    createdAt: iso("2026-08-14T22:00:10+02:00"),
    updatedAt: iso("2026-08-14T22:00:10+02:00"),
    visibility: "public",
    images: [],
  },
  {
    id: "act_seti",
    title: "SETI board game night",
    description: "We play SETI. I’ll teach. One table, no rush, snacks exist. Five seats including me.",
    type: "boardgames",
    tags: ["SETI", "Strategy", "Space"],
    lookingFor: ["Players"],
    location: { type: "in-person", city: "Belgrade", venue: "Play Board Game Cafe" },
    startAt: iso("2026-08-28T18:30:00+02:00"),
    endAt: iso("2026-08-28T23:00:00+02:00"),
    isFlexible: false,
    capacity: 5,
    joinPolicy: "auto",
    headcount: { mode: "limit", max: 5 },
    creatorId: "user_sam",
    creatorName: "Sam Okonkwo",
    creatorAvatar: null,
    memberCount: 2,
    status: "open",
    createdAt: iso("2026-08-14T22:00:08+02:00"),
    updatedAt: iso("2026-08-14T22:00:08+02:00"),
    visibility: "public",
    images: [],
  },
]

export function getActivity(id: string) {
  return MOCK_ACTIVITIES.find((activity) => activity.id === id) ?? null
}
